version: '3.8'
services:
  api:
    build: ./backend
    container_name: exam-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: exam-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
